# Generated by Django 2.2.5 on 2019-12-27 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='age',
        ),
    ]
